#include <stdio.h>

/**
 * main - Write a program that prints the first 50 Fibonacci numbers,
 * starting with 0.
 *
 * starting with 0.
 *
 * Return: the last digit of a number
 * --------------------------
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,
 * 89. By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program that finds and
 * prints the sum of the even-valued terms, followed by a new line.
 * --------------------------
 * By Youssef Hassane
 */
int main(void)
{
	int theFirst98Fibonacci(void);
	theFirst98Fibonacci();
	return (0);
}

/**
 * theFirst98Fibonacci - Write a program that prints the first
 * 50 Fibonacci numbers,
 * starting with 0.
 *
 * starting with 0.
 *
 * Return: the last digit of a number
 * --------------------------
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,
 * 89. By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program that finds and
 * prints the sum of the even-valued terms, followed by a new line.
 * --------------------------
 * By Youssef Hassane
 */
int theFirst98Fibonacci(void)
{
	/* Initialize variables */
	int count;
	unsigned long i, j, k;
	unsigned long m, n, p, carry;

	/* Initialize count and first two Fibonacci numbers */
	count = 0;
	i = 0;
	j = 1;

	/* Generate and print Fibonacci numbers up to the 91st number */
	for (count = 1; count <= 91; count++)
	{
		k = i + j;
		i = j;
		j = k;
		printf("%lu, ", k);
	}

	/* Prepare for handling larger numbers (grouping by 3 digits) */
	m = i % 1000;
	i = i / 1000;
	n = j % 1000;
	j = j / 1000;

	/* Generate and print the remaining Fibonacci numbers (92nd to 98th) */
	while (count <= 98)
	{
		carry = (m + n) / 1000;
		p = (m + n) - carry * 1000;
		k = (i + j) + carry;
		m = n;
		n = p;
		i = j;
		j = k;

		/* Format and print the current Fibonacci number */
		if (p >= 100)
			printf("%lu%lu", k, p);
		else
			printf("%lu0%lu", k, p);

		/* Add a comma and space unless it's the last number */
		if (count != 98)
			printf(", ");

		count++;
	}

	/* Print a newline character and return 0 to indicate success */
	putchar('\n');
	return (0);
}
